# Generated by Django 5.0.3 on 2024-03-27 12:05

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='employee_info',
            fields=[
                ('e_id', models.AutoField(primary_key=True, serialize=False, unique=True)),
                ('name', models.CharField(max_length=100)),
                ('phone', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=20)),
                ('nid_no', models.CharField(max_length=100)),
            ],
        ),
    ]
