# Generated by Django 5.0.3 on 2024-03-27 12:49

import django.db.models.deletion
import employeez_info.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employeez_info', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employee_info',
            name='email',
            field=models.EmailField(max_length=50),
        ),
        migrations.CreateModel(
            name='EmployeeImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to=employeez_info.models.employee_image_directory_path)),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='employeez_info.employee_info')),
            ],
        ),
    ]
