# Generated by Django 5.0.3 on 2024-03-27 14:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employeez_info', '0002_alter_employee_info_email_employeeimage'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employee_info',
            name='email',
            field=models.EmailField(max_length=50, unique=True),
        ),
        migrations.AlterField(
            model_name='employee_info',
            name='nid_no',
            field=models.CharField(max_length=100, unique=True),
        ),
        migrations.AlterField(
            model_name='employee_info',
            name='phone',
            field=models.CharField(max_length=100, unique=True),
        ),
    ]
